version: '3.7'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "9000:9000"
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    
  superset:
    image: apache/superset:latest
    container_name: superset
    ports:
      - "8088:8088"
    environment:
      SUPERSET_LOAD_EXAMPLES: "no"
      SUPERSET_DB_USER: "admin"
      SUPERSET_DB_PASS: "admin"
      SUPERSET_DB_NAME: "superset"
      SUPERSET_DB_HOST: "db"
      SUPERSET_SECRET_KEY: "thisISaSECRET_1234"
    depends_on:
      - clickhouse
    volumes:
      - superset-home:/app/superset_home
    command:
      - /bin/sh
      - -c
      - |
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin
        superset db upgrade
        superset init
        superset run -h 0.0.0.0 -p 8088

volumes:
  clickhouse-data:
  superset-home:
