apiVersion: v1
kind: Service
metadata:
  name: superset-service
spec:
  type: LoadBalancer
  selector:
    app: superset
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
